// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUlWkOJ8jYuV58SL9WbTW0tiFRzozhKPw',
    appId: '1:533672279361:web:de0e87244172363bd0b5c0',
    messagingSenderId: '533672279361',
    projectId: 'meal-idea-213',
    authDomain: 'meal-idea-213.firebaseapp.com',
    storageBucket: 'meal-idea-213.firebasestorage.app',
    measurementId: 'G-EPEH01ECRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy8qffQeeUuz2Go067ItJ51l7d5IoXRzU',
    appId: '1:533672279361:android:a92c69d82e6fd1d7d0b5c0',
    messagingSenderId: '533672279361',
    projectId: 'meal-idea-213',
    storageBucket: 'meal-idea-213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhOzaU2DAW9Z__0jXE0xjDDwp7IWubyLA',
    appId: '1:533672279361:ios:29ca98e30ac8907fd0b5c0',
    messagingSenderId: '533672279361',
    projectId: 'meal-idea-213',
    storageBucket: 'meal-idea-213.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhOzaU2DAW9Z__0jXE0xjDDwp7IWubyLA',
    appId: '1:533672279361:ios:29ca98e30ac8907fd0b5c0',
    messagingSenderId: '533672279361',
    projectId: 'meal-idea-213',
    storageBucket: 'meal-idea-213.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUlWkOJ8jYuV58SL9WbTW0tiFRzozhKPw',
    appId: '1:533672279361:web:3ceaef9169ba7b32d0b5c0',
    messagingSenderId: '533672279361',
    projectId: 'meal-idea-213',
    authDomain: 'meal-idea-213.firebaseapp.com',
    storageBucket: 'meal-idea-213.firebasestorage.app',
    measurementId: 'G-3GDW7DK1P6',
  );
}
